services:
  api:
    build: api/
    ports:
      - "8080:8080"

  app:
    build: app/
    environment:
      BACKEND_URL: https://recht-technisch-backend-339540402730.europe-west1.run.app
      PORT: 3000
    ports:
      - "3000:3000"
